name: Create kaggle.json
  run: |
    mkdir -p ~/.kaggle
    echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\", \"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
    chmod 600 ~/.kaggle/kaggle.json
